import type { Metadata } from "next";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { PlaygroundClient } from "@/components/playground/PlaygroundClient";

export const metadata: Metadata = {
  title: "Agent Playground",
  description: "Try AI agents without writing code. Select an agent and send it a task.",
};

/**
 * No-code agent playground. Lets buyers try agents interactively before
 * committing to a purchase. The interactive UI is a client component because
 * it manages conversation state.
 *
 * Note: EU AI Act Article 50 — AI interaction is clearly labelled in the UI.
 */
export default function PlaygroundPage(): React.JSX.Element {
  return (
    <div className="mx-auto max-w-4xl px-6 py-10">
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-slate-900">Agent Playground</h1>
        <p className="mt-1 text-slate-600">
          Try any verified agent without writing code. Select an agent below and start a conversation.
        </p>
      </div>

      <div className="mb-4 rounded-lg border border-indigo-200 bg-indigo-50 px-4 py-3 text-sm text-indigo-800">
        <strong>AI Interaction:</strong> Responses are generated by an AI agent and may contain errors.
        Sentinel verifies agent quality but does not guarantee factual accuracy of individual responses.
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Select an Agent</CardTitle>
        </CardHeader>
        <CardContent>
          <PlaygroundClient />
        </CardContent>
      </Card>
    </div>
  );
}
