import type { Metadata } from "next";
import { PlaygroundClient } from "@/components/playground/PlaygroundClient";

export const metadata: Metadata = {
  title: "Agent Playground",
  description: "Try AI agents without writing code. Select an agent and send it a task.",
};

/**
 * No-code agent playground. Lets buyers try agents interactively before
 * committing to a purchase. The interactive UI is a client component because
 * it manages conversation state.
 *
 * Note: EU AI Act Article 50 — AI interaction is clearly labelled in the UI.
 */
export default function PlaygroundPage(): React.JSX.Element {
  return (
    <div className="mx-auto max-w-6xl px-5 pb-24">
      {/* Page header */}
      <div className="mb-10">
        <span className="font-brand-mono text-xs uppercase tracking-[0.25em] text-gold">
          Playground
        </span>
        <h1 className="mt-3 text-4xl font-semibold text-porcelain">Agent Playground</h1>
        <p className="mt-3 max-w-2xl text-base text-porcelain/55">
          Try any verified agent without writing code. Select an agent below and start a
          conversation.
        </p>
      </div>

      {/* EU AI Act disclosure */}
      <div className="mb-6 rounded-xl border border-gold/20 bg-gold/8 px-4 py-3 text-sm text-gold/80">
        <strong className="font-semibold text-gold">AI Interaction:</strong> Responses are
        generated by an AI agent and may contain errors. Sentinel verifies agent quality but does
        not guarantee factual accuracy of individual responses.
      </div>

      {/* Playground panel */}
      <div className="overflow-hidden rounded-2xl glass ring-hairline">
        <div className="border-b border-porcelain/10 bg-ink-800/40 px-6 py-4">
          <h2 className="text-base font-semibold text-porcelain">Select an Agent</h2>
        </div>
        <div className="p-6">
          <PlaygroundClient />
        </div>
      </div>
    </div>
  );
}
